---
- block:
    - name: "Disable Flyway edition prior to version 5.2.0"
      set_fact:
        flyway_edition: None

    - name: "Ensure correct core jar path"
      set_fact:
        __flyway_core_jar: "{{ __flyway_core_jar_prior_5_2_0 }}"

  when: "flyway_version is version_compare('5.2.0','<')"

- name: "Ensure valid Flyway edition value"
  assert:
    that:
      - flyway_edition in __flyway_available_edition
    msg: "'flyway_edition' must be: 'community','pro','enterprise' or None."

- include_tasks: setup_rhe_prepare.yml
  when: (ansible_os_family == 'RedHat')

- include_tasks: setup_debian_prepare.yml
  when: (ansible_os_family == 'Debian') and (ansible_distribution != 'Ubuntu')

- include_tasks: setup_ubuntu18_prepare.yml
  when: (ansible_os_family == 'Debian') and (ansible_distribution == 'Ubuntu') and (ansible_distribution_major_version | int >= 18)

- include_tasks: setup_ubuntu_pre18_prepare.yml
  when: (ansible_os_family == 'Debian') and (ansible_distribution == 'Ubuntu') and (ansible_distribution_major_version | int < 18)
